### ISSUE TITLE
When processing multiple files, only one file gets generated, overriding previous ones.

### ISSUE THREAD

**Issue by EdSancha** [mattdanielmurphy/apple-podcast-transcript-extractor#1]
Let me start by saying that this script is great! Definitely using for taking notes.

Now, to the issue that I found and I encountered: 

I have two folders with several transcripts and, when running the script, I only get two files, while I have a couple dozen transcripts on the Podcast app.

I temporarily solved this using the loop index to differentiate each file. This is the snippet on line 108 on the js file with my quick and probably not great solution.

```
	ttmlFiles.forEach((file,index) => {
		const outputPath = path.join("./transcripts", `${file.id} - ${index}.txt`)
		const data = fs.readFileSync(file.path, "utf8")
		extractTranscript(data, outputPath, includeTimestamps)
	})
```

**Comment by mattdanielmurphy** [comment]
Thanks Ed!
I have not tested it much, so it's helpful to have this feedback—I updated the script so an incrementing suffix is added for files that have the same name.
